Samples in training set:
67105
[[list(['201604152305', '201604152310', '201604152315', '201604152320', '201604152325', '201604152330'])
  list(['201604160000', '201604160030', '201604160100'])]
 [list(['201710211805', '201710211810', '201710211815', '201710211820', '201710211825', '201710211830'])
  list(['201710211900', '201710211930', '201710212000'])]
 [list(['201611162135', '201611162140', '201611162145', '201611162150', '201611162155', '201611162200'])
  list(['201611162230', '201611162300', '201611162330'])]
 ...
 [list(['202002102335', '202002102340', '202002102345', '202002102350', '202002102355', '202002110000'])
  list(['202002110030', '202002110100', '202002110130'])]
 [list(['201411151635', '201411151640', '201411151645', '201411151650', '201411151655', '201411151700'])
  list(['201411151730', '201411151800', '201411151830'])]
 [list(['200806122305', '200806122310', '200806122315', '200806122320', '200806122325', '200806122330'])
  list(['200806130000', '200806130030', '200806130100'])]]
Samples in validation set:
6570
Traceback (most recent call last):
  File "E:/thesis_code/Large_Sample_Nowcasting_Evaluation/precipitation-nowcasting-using-GANs/precipitation_forecasting/testrun.py", line 97, in <module>
    history = model.fit(generator, validation_data = validation_generator, epochs = config.epochs,
  File "F:\anaconda\lib\site-packages\wandb\integration\keras\keras.py", line 168, in new_v2
    return old_v2(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "F:\anaconda\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1049, in fit
    data_handler = data_adapter.DataHandler(
  File "F:\anaconda\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1105, in __init__
    self._adapter = adapter_cls(
  File "F:\anaconda\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 909, in __init__
    super(KerasSequenceAdapter, self).__init__(
  File "F:\anaconda\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 786, in __init__
    peek, x = self._peek_and_restore(x)
  File "F:\anaconda\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 920, in _peek_and_restore
    return x[0], x
  File "E:\thesis_code\Large_Sample_Nowcasting_Evaluation\precipitation-nowcasting-using-GANs\precipitation_forecasting\batchcreator.py", line 95, in __getitem__
    X, y = self.__data_generation(list_IDs_temp)
  File "E:\thesis_code\Large_Sample_Nowcasting_Evaluation\precipitation-nowcasting-using-GANs\precipitation_forecasting\batchcreator.py", line 117, in __data_generation
    X[i,c] = self.load_x(x_IDs[c])
  File "E:\thesis_code\Large_Sample_Nowcasting_Evaluation\precipitation-nowcasting-using-GANs\precipitation_forecasting\batchcreator.py", line 216, in load_x
    x = np.load(path)
  File "F:\anaconda\lib\site-packages\numpy\lib\npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'E:/thesis_datasets/201001240135.npy'